INSERT INTO marvel_comics (name, published, issue, writer, cover_artist, details, img) VALUES
('Deadpool Nerdy 30', '2021','1', 'Joe Kelly', 'Ed Mcguiness','HE’S THE MERC WITH THE MOUTH! (FULL OF BIRTHDAY CAKE!) Deadpool’s turning 30! And to help celebrate, we’ve assembled some of his classic storytellers to tell tales of Wade Wilson birthdays past, present and future! A first birthday with time-traveling assassins! A sweet sixteen party that would make Molly Ringwald weep! A 100th birthday that could only be celebrated in grand Deadpool style! Blow out the candles! Pin the cybernetic arm on the Cable! And open this present, just for you!', 'deadpool_Nerdy30.jpeg'),
('Wolverine: Black, White & Blood', '2021', '4', 'Ed Brisson, Steve Deknight, Kelly Thompson', 'Khary Randolph', 'BRUTAL BATTLES WITH THE UNBREAKABLE MUTANT! The bloody, brutal mayhem continues! Steven S. DeKnight makes his debut in the Marvel Universe as he teams up with Paulo Siquiera to put the best there is through his paces on a bloody trip to the SAVAGE LAND! Kelly Thompson teams with Khary Randolph for a heartfelt — and heart-pounding — episode in Japan! And Ed Brisson takes LOGAN back to the Outback with Leonard Kirk, where he’ll go up against the REAVERS!', 'wolverine.jpeg'),
('Non-Stop Spider-Man', '2021', '1','Joe Kelly', 'David Finch', 'BUCKLE UP, TIGER! Get ready for the most action-packed, pulse-pounding, adrenaline-pumping comic OF ALL TIME! As the name implies, once you read page one, panel one, SPIDER-MAN DOES NOT STOP! A mystery at Empire State University thrusts Spider-Man into an adventure that starts in uptown Manhattan and will take him around the world, pitting him against Marvel Universe villains old and new and give you a Spider-Man adventure (and Spider-Man) the likes of which you’ve never seen. THIS BOOK IS NOT FOR THE FAINT OF HEART, SO CHECK WITH YOUR DOCTOR BEFORE READING!', 'nonstop_spider.jpeg'),
('Thor & Loki: Double Trouble', '2021', '1', 'Mariko Tamaki', 'G Gurihiru', 'They’re brothers, gods and sons of Odin — but Thor and Loki just don’t get along! Especially since Loki keeps tricking Thor into doing things that will get him in trouble. Even so, when Loki dares Thor to steal a powerful relic from Odin’s vault, how can the God of Thunder say nay? The fan-favorite team that brought you SPIDER-MAN & VENOM: DOUBLE TROUBLE returns!', 'double_trouble'),
('Importal Hulk', '2021', '44', 'Al Ewing','Joe Bennett', 'In New York, the U-Foes are hunting a weakened Hulk - with the one thing that can kill him for good. In New Mexico, the new Sasquatch faces something even weirder than he is. Something very strange is happening to Jacqueline McGee. And far above the world, HENRY PETER GYRICH watches...', 'Immortal_hulk.jpeg'),
('Daredevil', '2019', '28', 'Chip Zdarsky', 'Marco Checchetto', 'A NEW DAREDEVIL RISES TO PROTECT HELL’S KITCHEN! Matt Murdock is a killer – but while he’s serving his time as the masked vigilante called Daredevil, Hell’s Kitchen has suddenly been left without a guardian devil. Or it was, until ELEKTRA NATCHIOS took it upon herself to protect Murdock’s neighborhood and his legacy as the NEW DAREDEVIL! But she’s already got her work cut out for her: WILSON FISK remains seated as New York’s mayor, with TYPHOID MARY, THE OWL, HAMMERHEAD and other lethal – and FAMILIAR – foes at his beck and call...', 'daredevil.jpeg'),
('The Amazing Spider-Man', '2021', '61', 'Nick Spencer', 'Patrick Gleason', 'Peter Parker gets a new job! Spidey gets a new look! And Kingpin’s plans start coming together!', 'Amazing_spider.jpeg'),
('Eternals', '2021', '3', 'Kieron Gillen', 'Esad Ribic', 'Journey to the heart of the DEVIANT CITY! Come berserk Lemuria, home of the Deviants, city of a 12 million species. An Eternal has been murdered by one of their own. And Sersi’s number one suspect is…Thena?! Plus, why is Ikaris so interested in the fate of a human boy?', 'Eternals.jpeg'),
('Star Wars', '2020', '12', 'Charles Soule', 'Carlo Pagualayan', 'REFLECTIONS ON THE LOST! LEIA ORGANA and KES DAMERON share stories of their lost loves! Learn how POE DAMERON’S parents met! Learn the real reason HAN SOLO is so important to THE REBELLION!', 'Star_Wars.jpeg'),
('Strange Academy', '2020', '9', 'Skottie Young', 'Humberto Ramos', 'It’s PARENTS’ DAY at Strange Academy! For most students, it’s a joyous day, but for Calvin Morse, an orphan…not so much. So while the rest of the parents go on a scavenger hunt around campus, Calvin and an unlikely friend face something truly scary.', 'Strange.jpeg'),
('Taskmaster', '2020', '4', 'Jed Mackay', 'Valerio Giangiordano', 'TARGET: OKOYE! The Rubicon Trigger is a doomsday device that the world’s greatest superspies thought they had locked away forever — until someone murdered MARIA HILL to get to it! Taskmaster’s next stop to prevent global destruction? Sunny Wakanda, of course! Home to Okoye and the feared Dogs of War!', 'Task_master.jpeg'),
('X-Factor', '2020', '8', 'Leah Williams', 'Ivan Shavrin', 'Cover by Ivan Shavrin Hey, guys! Wasn’t expecting to see X-Factor torpedo up the resurrection queue priority--. Boneyard’s haunted. WHAT? *Resurrecting murdered teammates* Boneyard’s haunted.', 'X-factor.jpeg');
